rm: cannot remove ‘data_diagonal_density/diagonal_density_contributions_0_1_0_WC3.0.dat’: No such file or directory
Reading Upol file 0 of 5
Reading Upol file 1 of 5
Reading Upol file 2 of 5
Reading Upol file 3 of 5
Reading Upol file 4 of 5
	NAtoms   = 14
	TD Grid  = -12
	Nx Ny Nz = 75 75 75
	Lx Ly Lz = 6.597639861 5.149145286 2.9992252770000003 A
	Volume   = 101.89029951748621 A^3
	Memory size of transition density array in (MB, GB): (8437.5,8.44)
	Reading Transition Density: 0-0.
	Reading Transition Density: 0-1.
	Reading Transition Density: 0-2.
	Reading Transition Density: 0-3.
	Reading Transition Density: 0-4.
	Reading Transition Density: 0-5.
	Reading Transition Density: 0-6.
	Reading Transition Density: 0-7.
	Reading Transition Density: 0-8.
	Reading Transition Density: 0-9.
	Reading Transition Density: 0-10.
	Reading Transition Density: 0-11.
	Reading Transition Density: 0-12.
	Reading Transition Density: 0-13.
	Reading Transition Density: 0-14.
	Reading Transition Density: 0-15.
	Reading Transition Density: 0-16.
	Reading Transition Density: 0-17.
	Reading Transition Density: 0-18.
	Reading Transition Density: 0-19.
	Reading Transition Density: 0-20.
	Reading Transition Density: 0-21.
	Reading Transition Density: 0-22.
	Reading Transition Density: 0-23.
	Reading Transition Density: 0-24.
	Reading Transition Density: 0-25.
	Reading Transition Density: 0-26.
	Reading Transition Density: 0-27.
	Reading Transition Density: 0-28.
	Reading Transition Density: 0-29.
	Reading Transition Density: 0-30.
	Reading Transition Density: 0-31.
	Reading Transition Density: 0-32.
	Reading Transition Density: 0-33.
	Reading Transition Density: 0-34.
	Reading Transition Density: 0-35.
	Reading Transition Density: 0-36.
	Reading Transition Density: 0-37.
	Reading Transition Density: 0-38.
	Reading Transition Density: 0-39.
	Reading Transition Density: 0-40.
	Reading Transition Density: 0-41.
	Reading Transition Density: 0-42.
	Reading Transition Density: 0-43.
	Reading Transition Density: 0-44.
	Reading Transition Density: 0-45.
	Reading Transition Density: 0-46.
	Reading Transition Density: 0-47.
	Reading Transition Density: 0-48.
	Reading Transition Density: 0-49.
	Reading Transition Density: 1-1.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02535769495045
	Reading Transition Density: 1-2.
	****** File "trans-1_2.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-3.
	****** File "trans-1_3.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-4.
	****** File "trans-1_4.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-5.
	****** File "trans-1_5.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-6.
	****** File "trans-1_6.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-7.
	****** File "trans-1_7.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-8.
	****** File "trans-1_8.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-9.
	****** File "trans-1_9.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-10.
	****** File "trans-1_10.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-11.
	****** File "trans-1_11.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-12.
	****** File "trans-1_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-13.
	****** File "trans-1_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-14.
	****** File "trans-1_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-15.
	****** File "trans-1_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-16.
	****** File "trans-1_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-17.
	****** File "trans-1_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-18.
	****** File "trans-1_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-19.
	****** File "trans-1_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-20.
	****** File "trans-1_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-21.
	****** File "trans-1_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-22.
	****** File "trans-1_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-23.
	****** File "trans-1_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-24.
	****** File "trans-1_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-25.
	****** File "trans-1_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-26.
	****** File "trans-1_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-27.
	****** File "trans-1_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-28.
	****** File "trans-1_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-29.
	****** File "trans-1_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-30.
	****** File "trans-1_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-31.
	****** File "trans-1_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-32.
	****** File "trans-1_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-33.
	****** File "trans-1_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-34.
	****** File "trans-1_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-35.
	****** File "trans-1_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-36.
	****** File "trans-1_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-37.
	****** File "trans-1_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-38.
	****** File "trans-1_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-39.
	****** File "trans-1_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-40.
	****** File "trans-1_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-41.
	****** File "trans-1_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-42.
	****** File "trans-1_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-43.
	****** File "trans-1_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-44.
	****** File "trans-1_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-45.
	****** File "trans-1_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-46.
	****** File "trans-1_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-47.
	****** File "trans-1_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-48.
	****** File "trans-1_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 1-49.
	****** File "trans-1_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-2.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02495507206489
	Reading Transition Density: 2-3.
	****** File "trans-2_3.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-4.
	****** File "trans-2_4.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-5.
	****** File "trans-2_5.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-6.
	****** File "trans-2_6.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-7.
	****** File "trans-2_7.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-8.
	****** File "trans-2_8.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-9.
	****** File "trans-2_9.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-10.
	****** File "trans-2_10.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-11.
	****** File "trans-2_11.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-12.
	****** File "trans-2_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-13.
	****** File "trans-2_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-14.
	****** File "trans-2_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-15.
	****** File "trans-2_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-16.
	****** File "trans-2_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-17.
	****** File "trans-2_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-18.
	****** File "trans-2_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-19.
	****** File "trans-2_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-20.
	****** File "trans-2_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-21.
	****** File "trans-2_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-22.
	****** File "trans-2_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-23.
	****** File "trans-2_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-24.
	****** File "trans-2_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-25.
	****** File "trans-2_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-26.
	****** File "trans-2_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-27.
	****** File "trans-2_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-28.
	****** File "trans-2_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-29.
	****** File "trans-2_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-30.
	****** File "trans-2_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-31.
	****** File "trans-2_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-32.
	****** File "trans-2_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-33.
	****** File "trans-2_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-34.
	****** File "trans-2_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-35.
	****** File "trans-2_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-36.
	****** File "trans-2_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-37.
	****** File "trans-2_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-38.
	****** File "trans-2_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-39.
	****** File "trans-2_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-40.
	****** File "trans-2_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-41.
	****** File "trans-2_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-42.
	****** File "trans-2_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-43.
	****** File "trans-2_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-44.
	****** File "trans-2_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-45.
	****** File "trans-2_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-46.
	****** File "trans-2_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-47.
	****** File "trans-2_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-48.
	****** File "trans-2_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 2-49.
	****** File "trans-2_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-3.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02593968381018
	Reading Transition Density: 3-4.
	****** File "trans-3_4.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-5.
	****** File "trans-3_5.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-6.
	****** File "trans-3_6.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-7.
	****** File "trans-3_7.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-8.
	****** File "trans-3_8.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-9.
	****** File "trans-3_9.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-10.
	****** File "trans-3_10.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-11.
	****** File "trans-3_11.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-12.
	****** File "trans-3_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-13.
	****** File "trans-3_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-14.
	****** File "trans-3_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-15.
	****** File "trans-3_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-16.
	****** File "trans-3_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-17.
	****** File "trans-3_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-18.
	****** File "trans-3_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-19.
	****** File "trans-3_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-20.
	****** File "trans-3_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-21.
	****** File "trans-3_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-22.
	****** File "trans-3_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-23.
	****** File "trans-3_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-24.
	****** File "trans-3_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-25.
	****** File "trans-3_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-26.
	****** File "trans-3_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-27.
	****** File "trans-3_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-28.
	****** File "trans-3_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-29.
	****** File "trans-3_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-30.
	****** File "trans-3_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-31.
	****** File "trans-3_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-32.
	****** File "trans-3_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-33.
	****** File "trans-3_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-34.
	****** File "trans-3_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-35.
	****** File "trans-3_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-36.
	****** File "trans-3_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-37.
	****** File "trans-3_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-38.
	****** File "trans-3_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-39.
	****** File "trans-3_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-40.
	****** File "trans-3_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-41.
	****** File "trans-3_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-42.
	****** File "trans-3_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-43.
	****** File "trans-3_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-44.
	****** File "trans-3_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-45.
	****** File "trans-3_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-46.
	****** File "trans-3_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-47.
	****** File "trans-3_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-48.
	****** File "trans-3_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 3-49.
	****** File "trans-3_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-4.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02592990088095
	Reading Transition Density: 4-5.
	****** File "trans-4_5.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-6.
	****** File "trans-4_6.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-7.
	****** File "trans-4_7.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-8.
	****** File "trans-4_8.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-9.
	****** File "trans-4_9.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-10.
	****** File "trans-4_10.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-11.
	****** File "trans-4_11.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-12.
	****** File "trans-4_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-13.
	****** File "trans-4_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-14.
	****** File "trans-4_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-15.
	****** File "trans-4_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-16.
	****** File "trans-4_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-17.
	****** File "trans-4_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-18.
	****** File "trans-4_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-19.
	****** File "trans-4_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-20.
	****** File "trans-4_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-21.
	****** File "trans-4_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-22.
	****** File "trans-4_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-23.
	****** File "trans-4_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-24.
	****** File "trans-4_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-25.
	****** File "trans-4_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-26.
	****** File "trans-4_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-27.
	****** File "trans-4_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-28.
	****** File "trans-4_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-29.
	****** File "trans-4_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-30.
	****** File "trans-4_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-31.
	****** File "trans-4_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-32.
	****** File "trans-4_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-33.
	****** File "trans-4_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-34.
	****** File "trans-4_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-35.
	****** File "trans-4_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-36.
	****** File "trans-4_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-37.
	****** File "trans-4_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-38.
	****** File "trans-4_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-39.
	****** File "trans-4_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-40.
	****** File "trans-4_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-41.
	****** File "trans-4_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-42.
	****** File "trans-4_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-43.
	****** File "trans-4_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-44.
	****** File "trans-4_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-45.
	****** File "trans-4_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-46.
	****** File "trans-4_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-47.
	****** File "trans-4_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-48.
	****** File "trans-4_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 4-49.
	****** File "trans-4_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-5.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025908214941936
	Reading Transition Density: 5-6.
	****** File "trans-5_6.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-7.
	****** File "trans-5_7.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-8.
	****** File "trans-5_8.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-9.
	****** File "trans-5_9.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-10.
	****** File "trans-5_10.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-11.
	****** File "trans-5_11.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-12.
	****** File "trans-5_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-13.
	****** File "trans-5_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-14.
	****** File "trans-5_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-15.
	****** File "trans-5_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-16.
	****** File "trans-5_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-17.
	****** File "trans-5_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-18.
	****** File "trans-5_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-19.
	****** File "trans-5_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-20.
	****** File "trans-5_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-21.
	****** File "trans-5_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-22.
	****** File "trans-5_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-23.
	****** File "trans-5_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-24.
	****** File "trans-5_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-25.
	****** File "trans-5_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-26.
	****** File "trans-5_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-27.
	****** File "trans-5_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-28.
	****** File "trans-5_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-29.
	****** File "trans-5_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-30.
	****** File "trans-5_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-31.
	****** File "trans-5_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-32.
	****** File "trans-5_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-33.
	****** File "trans-5_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-34.
	****** File "trans-5_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-35.
	****** File "trans-5_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-36.
	****** File "trans-5_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-37.
	****** File "trans-5_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-38.
	****** File "trans-5_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-39.
	****** File "trans-5_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-40.
	****** File "trans-5_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-41.
	****** File "trans-5_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-42.
	****** File "trans-5_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-43.
	****** File "trans-5_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-44.
	****** File "trans-5_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-45.
	****** File "trans-5_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-46.
	****** File "trans-5_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-47.
	****** File "trans-5_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-48.
	****** File "trans-5_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 5-49.
	****** File "trans-5_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-6.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025941429561065
	Reading Transition Density: 6-7.
	****** File "trans-6_7.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-8.
	****** File "trans-6_8.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-9.
	****** File "trans-6_9.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-10.
	****** File "trans-6_10.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-11.
	****** File "trans-6_11.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-12.
	****** File "trans-6_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-13.
	****** File "trans-6_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-14.
	****** File "trans-6_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-15.
	****** File "trans-6_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-16.
	****** File "trans-6_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-17.
	****** File "trans-6_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-18.
	****** File "trans-6_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-19.
	****** File "trans-6_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-20.
	****** File "trans-6_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-21.
	****** File "trans-6_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-22.
	****** File "trans-6_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-23.
	****** File "trans-6_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-24.
	****** File "trans-6_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-25.
	****** File "trans-6_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-26.
	****** File "trans-6_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-27.
	****** File "trans-6_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-28.
	****** File "trans-6_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-29.
	****** File "trans-6_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-30.
	****** File "trans-6_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-31.
	****** File "trans-6_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-32.
	****** File "trans-6_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-33.
	****** File "trans-6_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-34.
	****** File "trans-6_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-35.
	****** File "trans-6_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-36.
	****** File "trans-6_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-37.
	****** File "trans-6_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-38.
	****** File "trans-6_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-39.
	****** File "trans-6_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-40.
	****** File "trans-6_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-41.
	****** File "trans-6_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-42.
	****** File "trans-6_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-43.
	****** File "trans-6_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-44.
	****** File "trans-6_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-45.
	****** File "trans-6_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-46.
	****** File "trans-6_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-47.
	****** File "trans-6_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-48.
	****** File "trans-6_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 6-49.
	****** File "trans-6_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-7.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02594907657988
	Reading Transition Density: 7-8.
	****** File "trans-7_8.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-9.
	****** File "trans-7_9.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-10.
	****** File "trans-7_10.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-11.
	****** File "trans-7_11.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-12.
	****** File "trans-7_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-13.
	****** File "trans-7_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-14.
	****** File "trans-7_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-15.
	****** File "trans-7_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-16.
	****** File "trans-7_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-17.
	****** File "trans-7_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-18.
	****** File "trans-7_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-19.
	****** File "trans-7_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-20.
	****** File "trans-7_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-21.
	****** File "trans-7_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-22.
	****** File "trans-7_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-23.
	****** File "trans-7_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-24.
	****** File "trans-7_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-25.
	****** File "trans-7_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-26.
	****** File "trans-7_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-27.
	****** File "trans-7_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-28.
	****** File "trans-7_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-29.
	****** File "trans-7_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-30.
	****** File "trans-7_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-31.
	****** File "trans-7_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-32.
	****** File "trans-7_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-33.
	****** File "trans-7_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-34.
	****** File "trans-7_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-35.
	****** File "trans-7_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-36.
	****** File "trans-7_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-37.
	****** File "trans-7_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-38.
	****** File "trans-7_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-39.
	****** File "trans-7_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-40.
	****** File "trans-7_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-41.
	****** File "trans-7_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-42.
	****** File "trans-7_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-43.
	****** File "trans-7_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-44.
	****** File "trans-7_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-45.
	****** File "trans-7_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-46.
	****** File "trans-7_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-47.
	****** File "trans-7_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-48.
	****** File "trans-7_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 7-49.
	****** File "trans-7_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-8.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.0258717264451
	Reading Transition Density: 8-9.
	****** File "trans-8_9.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-10.
	****** File "trans-8_10.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-11.
	****** File "trans-8_11.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-12.
	****** File "trans-8_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-13.
	****** File "trans-8_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-14.
	****** File "trans-8_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-15.
	****** File "trans-8_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-16.
	****** File "trans-8_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-17.
	****** File "trans-8_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-18.
	****** File "trans-8_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-19.
	****** File "trans-8_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-20.
	****** File "trans-8_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-21.
	****** File "trans-8_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-22.
	****** File "trans-8_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-23.
	****** File "trans-8_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-24.
	****** File "trans-8_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-25.
	****** File "trans-8_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-26.
	****** File "trans-8_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-27.
	****** File "trans-8_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-28.
	****** File "trans-8_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-29.
	****** File "trans-8_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-30.
	****** File "trans-8_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-31.
	****** File "trans-8_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-32.
	****** File "trans-8_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-33.
	****** File "trans-8_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-34.
	****** File "trans-8_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-35.
	****** File "trans-8_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-36.
	****** File "trans-8_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-37.
	****** File "trans-8_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-38.
	****** File "trans-8_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-39.
	****** File "trans-8_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-40.
	****** File "trans-8_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-41.
	****** File "trans-8_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-42.
	****** File "trans-8_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-43.
	****** File "trans-8_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-44.
	****** File "trans-8_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-45.
	****** File "trans-8_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-46.
	****** File "trans-8_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-47.
	****** File "trans-8_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-48.
	****** File "trans-8_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 8-49.
	****** File "trans-8_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-9.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02585034015485
	Reading Transition Density: 9-10.
	****** File "trans-9_10.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-11.
	****** File "trans-9_11.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-12.
	****** File "trans-9_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-13.
	****** File "trans-9_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-14.
	****** File "trans-9_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-15.
	****** File "trans-9_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-16.
	****** File "trans-9_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-17.
	****** File "trans-9_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-18.
	****** File "trans-9_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-19.
	****** File "trans-9_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-20.
	****** File "trans-9_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-21.
	****** File "trans-9_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-22.
	****** File "trans-9_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-23.
	****** File "trans-9_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-24.
	****** File "trans-9_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-25.
	****** File "trans-9_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-26.
	****** File "trans-9_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-27.
	****** File "trans-9_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-28.
	****** File "trans-9_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-29.
	****** File "trans-9_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-30.
	****** File "trans-9_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-31.
	****** File "trans-9_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-32.
	****** File "trans-9_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-33.
	****** File "trans-9_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-34.
	****** File "trans-9_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-35.
	****** File "trans-9_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-36.
	****** File "trans-9_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-37.
	****** File "trans-9_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-38.
	****** File "trans-9_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-39.
	****** File "trans-9_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-40.
	****** File "trans-9_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-41.
	****** File "trans-9_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-42.
	****** File "trans-9_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-43.
	****** File "trans-9_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-44.
	****** File "trans-9_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-45.
	****** File "trans-9_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-46.
	****** File "trans-9_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-47.
	****** File "trans-9_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-48.
	****** File "trans-9_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 9-49.
	****** File "trans-9_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-10.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025599454862935
	Reading Transition Density: 10-11.
	****** File "trans-10_11.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-12.
	****** File "trans-10_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-13.
	****** File "trans-10_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-14.
	****** File "trans-10_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-15.
	****** File "trans-10_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-16.
	****** File "trans-10_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-17.
	****** File "trans-10_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-18.
	****** File "trans-10_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-19.
	****** File "trans-10_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-20.
	****** File "trans-10_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-21.
	****** File "trans-10_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-22.
	****** File "trans-10_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-23.
	****** File "trans-10_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-24.
	****** File "trans-10_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-25.
	****** File "trans-10_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-26.
	****** File "trans-10_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-27.
	****** File "trans-10_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-28.
	****** File "trans-10_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-29.
	****** File "trans-10_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-30.
	****** File "trans-10_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-31.
	****** File "trans-10_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-32.
	****** File "trans-10_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-33.
	****** File "trans-10_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-34.
	****** File "trans-10_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-35.
	****** File "trans-10_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-36.
	****** File "trans-10_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-37.
	****** File "trans-10_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-38.
	****** File "trans-10_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-39.
	****** File "trans-10_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-40.
	****** File "trans-10_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-41.
	****** File "trans-10_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-42.
	****** File "trans-10_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-43.
	****** File "trans-10_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-44.
	****** File "trans-10_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-45.
	****** File "trans-10_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-46.
	****** File "trans-10_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-47.
	****** File "trans-10_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-48.
	****** File "trans-10_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 10-49.
	****** File "trans-10_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-11.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025297339251935
	Reading Transition Density: 11-12.
	****** File "trans-11_12.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-13.
	****** File "trans-11_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-14.
	****** File "trans-11_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-15.
	****** File "trans-11_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-16.
	****** File "trans-11_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-17.
	****** File "trans-11_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-18.
	****** File "trans-11_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-19.
	****** File "trans-11_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-20.
	****** File "trans-11_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-21.
	****** File "trans-11_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-22.
	****** File "trans-11_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-23.
	****** File "trans-11_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-24.
	****** File "trans-11_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-25.
	****** File "trans-11_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-26.
	****** File "trans-11_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-27.
	****** File "trans-11_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-28.
	****** File "trans-11_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-29.
	****** File "trans-11_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-30.
	****** File "trans-11_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-31.
	****** File "trans-11_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-32.
	****** File "trans-11_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-33.
	****** File "trans-11_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-34.
	****** File "trans-11_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-35.
	****** File "trans-11_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-36.
	****** File "trans-11_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-37.
	****** File "trans-11_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-38.
	****** File "trans-11_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-39.
	****** File "trans-11_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-40.
	****** File "trans-11_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-41.
	****** File "trans-11_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-42.
	****** File "trans-11_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-43.
	****** File "trans-11_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-44.
	****** File "trans-11_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-45.
	****** File "trans-11_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-46.
	****** File "trans-11_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-47.
	****** File "trans-11_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-48.
	****** File "trans-11_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 11-49.
	****** File "trans-11_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-12.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02594121567118
	Reading Transition Density: 12-13.
	****** File "trans-12_13.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-14.
	****** File "trans-12_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-15.
	****** File "trans-12_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-16.
	****** File "trans-12_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-17.
	****** File "trans-12_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-18.
	****** File "trans-12_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-19.
	****** File "trans-12_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-20.
	****** File "trans-12_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-21.
	****** File "trans-12_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-22.
	****** File "trans-12_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-23.
	****** File "trans-12_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-24.
	****** File "trans-12_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-25.
	****** File "trans-12_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-26.
	****** File "trans-12_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-27.
	****** File "trans-12_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-28.
	****** File "trans-12_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-29.
	****** File "trans-12_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-30.
	****** File "trans-12_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-31.
	****** File "trans-12_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-32.
	****** File "trans-12_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-33.
	****** File "trans-12_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-34.
	****** File "trans-12_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-35.
	****** File "trans-12_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-36.
	****** File "trans-12_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-37.
	****** File "trans-12_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-38.
	****** File "trans-12_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-39.
	****** File "trans-12_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-40.
	****** File "trans-12_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-41.
	****** File "trans-12_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-42.
	****** File "trans-12_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-43.
	****** File "trans-12_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-44.
	****** File "trans-12_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-45.
	****** File "trans-12_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-46.
	****** File "trans-12_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-47.
	****** File "trans-12_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-48.
	****** File "trans-12_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 12-49.
	****** File "trans-12_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-13.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025937792671655
	Reading Transition Density: 13-14.
	****** File "trans-13_14.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-15.
	****** File "trans-13_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-16.
	****** File "trans-13_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-17.
	****** File "trans-13_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-18.
	****** File "trans-13_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-19.
	****** File "trans-13_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-20.
	****** File "trans-13_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-21.
	****** File "trans-13_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-22.
	****** File "trans-13_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-23.
	****** File "trans-13_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-24.
	****** File "trans-13_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-25.
	****** File "trans-13_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-26.
	****** File "trans-13_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-27.
	****** File "trans-13_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-28.
	****** File "trans-13_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-29.
	****** File "trans-13_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-30.
	****** File "trans-13_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-31.
	****** File "trans-13_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-32.
	****** File "trans-13_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-33.
	****** File "trans-13_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-34.
	****** File "trans-13_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-35.
	****** File "trans-13_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-36.
	****** File "trans-13_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-37.
	****** File "trans-13_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-38.
	****** File "trans-13_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-39.
	****** File "trans-13_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-40.
	****** File "trans-13_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-41.
	****** File "trans-13_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-42.
	****** File "trans-13_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-43.
	****** File "trans-13_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-44.
	****** File "trans-13_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-45.
	****** File "trans-13_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-46.
	****** File "trans-13_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-47.
	****** File "trans-13_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-48.
	****** File "trans-13_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 13-49.
	****** File "trans-13_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-14.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02529607115282
	Reading Transition Density: 14-15.
	****** File "trans-14_15.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-16.
	****** File "trans-14_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-17.
	****** File "trans-14_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-18.
	****** File "trans-14_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-19.
	****** File "trans-14_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-20.
	****** File "trans-14_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-21.
	****** File "trans-14_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-22.
	****** File "trans-14_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-23.
	****** File "trans-14_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-24.
	****** File "trans-14_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-25.
	****** File "trans-14_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-26.
	****** File "trans-14_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-27.
	****** File "trans-14_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-28.
	****** File "trans-14_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-29.
	****** File "trans-14_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-30.
	****** File "trans-14_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-31.
	****** File "trans-14_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-32.
	****** File "trans-14_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-33.
	****** File "trans-14_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-34.
	****** File "trans-14_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-35.
	****** File "trans-14_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-36.
	****** File "trans-14_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-37.
	****** File "trans-14_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-38.
	****** File "trans-14_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-39.
	****** File "trans-14_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-40.
	****** File "trans-14_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-41.
	****** File "trans-14_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-42.
	****** File "trans-14_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-43.
	****** File "trans-14_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-44.
	****** File "trans-14_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-45.
	****** File "trans-14_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-46.
	****** File "trans-14_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-47.
	****** File "trans-14_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-48.
	****** File "trans-14_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 14-49.
	****** File "trans-14_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-15.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.026015109284764
	Reading Transition Density: 15-16.
	****** File "trans-15_16.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-17.
	****** File "trans-15_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-18.
	****** File "trans-15_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-19.
	****** File "trans-15_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-20.
	****** File "trans-15_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-21.
	****** File "trans-15_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-22.
	****** File "trans-15_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-23.
	****** File "trans-15_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-24.
	****** File "trans-15_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-25.
	****** File "trans-15_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-26.
	****** File "trans-15_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-27.
	****** File "trans-15_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-28.
	****** File "trans-15_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-29.
	****** File "trans-15_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-30.
	****** File "trans-15_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-31.
	****** File "trans-15_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-32.
	****** File "trans-15_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-33.
	****** File "trans-15_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-34.
	****** File "trans-15_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-35.
	****** File "trans-15_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-36.
	****** File "trans-15_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-37.
	****** File "trans-15_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-38.
	****** File "trans-15_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-39.
	****** File "trans-15_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-40.
	****** File "trans-15_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-41.
	****** File "trans-15_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-42.
	****** File "trans-15_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-43.
	****** File "trans-15_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-44.
	****** File "trans-15_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-45.
	****** File "trans-15_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-46.
	****** File "trans-15_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-47.
	****** File "trans-15_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-48.
	****** File "trans-15_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 15-49.
	****** File "trans-15_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-16.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02514291949302
	Reading Transition Density: 16-17.
	****** File "trans-16_17.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-18.
	****** File "trans-16_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-19.
	****** File "trans-16_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-20.
	****** File "trans-16_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-21.
	****** File "trans-16_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-22.
	****** File "trans-16_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-23.
	****** File "trans-16_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-24.
	****** File "trans-16_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-25.
	****** File "trans-16_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-26.
	****** File "trans-16_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-27.
	****** File "trans-16_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-28.
	****** File "trans-16_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-29.
	****** File "trans-16_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-30.
	****** File "trans-16_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-31.
	****** File "trans-16_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-32.
	****** File "trans-16_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-33.
	****** File "trans-16_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-34.
	****** File "trans-16_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-35.
	****** File "trans-16_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-36.
	****** File "trans-16_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-37.
	****** File "trans-16_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-38.
	****** File "trans-16_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-39.
	****** File "trans-16_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-40.
	****** File "trans-16_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-41.
	****** File "trans-16_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-42.
	****** File "trans-16_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-43.
	****** File "trans-16_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-44.
	****** File "trans-16_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-45.
	****** File "trans-16_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-46.
	****** File "trans-16_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-47.
	****** File "trans-16_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-48.
	****** File "trans-16_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 16-49.
	****** File "trans-16_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-17.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02593842307812
	Reading Transition Density: 17-18.
	****** File "trans-17_18.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-19.
	****** File "trans-17_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-20.
	****** File "trans-17_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-21.
	****** File "trans-17_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-22.
	****** File "trans-17_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-23.
	****** File "trans-17_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-24.
	****** File "trans-17_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-25.
	****** File "trans-17_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-26.
	****** File "trans-17_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-27.
	****** File "trans-17_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-28.
	****** File "trans-17_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-29.
	****** File "trans-17_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-30.
	****** File "trans-17_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-31.
	****** File "trans-17_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-32.
	****** File "trans-17_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-33.
	****** File "trans-17_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-34.
	****** File "trans-17_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-35.
	****** File "trans-17_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-36.
	****** File "trans-17_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-37.
	****** File "trans-17_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-38.
	****** File "trans-17_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-39.
	****** File "trans-17_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-40.
	****** File "trans-17_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-41.
	****** File "trans-17_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-42.
	****** File "trans-17_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-43.
	****** File "trans-17_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-44.
	****** File "trans-17_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-45.
	****** File "trans-17_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-46.
	****** File "trans-17_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-47.
	****** File "trans-17_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-48.
	****** File "trans-17_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 17-49.
	****** File "trans-17_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-18.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02591330159699
	Reading Transition Density: 18-19.
	****** File "trans-18_19.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-20.
	****** File "trans-18_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-21.
	****** File "trans-18_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-22.
	****** File "trans-18_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-23.
	****** File "trans-18_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-24.
	****** File "trans-18_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-25.
	****** File "trans-18_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-26.
	****** File "trans-18_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-27.
	****** File "trans-18_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-28.
	****** File "trans-18_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-29.
	****** File "trans-18_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-30.
	****** File "trans-18_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-31.
	****** File "trans-18_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-32.
	****** File "trans-18_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-33.
	****** File "trans-18_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-34.
	****** File "trans-18_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-35.
	****** File "trans-18_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-36.
	****** File "trans-18_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-37.
	****** File "trans-18_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-38.
	****** File "trans-18_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-39.
	****** File "trans-18_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-40.
	****** File "trans-18_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-41.
	****** File "trans-18_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-42.
	****** File "trans-18_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-43.
	****** File "trans-18_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-44.
	****** File "trans-18_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-45.
	****** File "trans-18_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-46.
	****** File "trans-18_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-47.
	****** File "trans-18_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-48.
	****** File "trans-18_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 18-49.
	****** File "trans-18_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-19.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025969024006606
	Reading Transition Density: 19-20.
	****** File "trans-19_20.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-21.
	****** File "trans-19_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-22.
	****** File "trans-19_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-23.
	****** File "trans-19_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-24.
	****** File "trans-19_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-25.
	****** File "trans-19_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-26.
	****** File "trans-19_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-27.
	****** File "trans-19_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-28.
	****** File "trans-19_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-29.
	****** File "trans-19_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-30.
	****** File "trans-19_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-31.
	****** File "trans-19_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-32.
	****** File "trans-19_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-33.
	****** File "trans-19_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-34.
	****** File "trans-19_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-35.
	****** File "trans-19_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-36.
	****** File "trans-19_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-37.
	****** File "trans-19_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-38.
	****** File "trans-19_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-39.
	****** File "trans-19_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-40.
	****** File "trans-19_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-41.
	****** File "trans-19_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-42.
	****** File "trans-19_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-43.
	****** File "trans-19_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-44.
	****** File "trans-19_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-45.
	****** File "trans-19_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-46.
	****** File "trans-19_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-47.
	****** File "trans-19_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-48.
	****** File "trans-19_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 19-49.
	****** File "trans-19_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-20.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025983447612525
	Reading Transition Density: 20-21.
	****** File "trans-20_21.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-22.
	****** File "trans-20_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-23.
	****** File "trans-20_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-24.
	****** File "trans-20_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-25.
	****** File "trans-20_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-26.
	****** File "trans-20_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-27.
	****** File "trans-20_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-28.
	****** File "trans-20_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-29.
	****** File "trans-20_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-30.
	****** File "trans-20_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-31.
	****** File "trans-20_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-32.
	****** File "trans-20_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-33.
	****** File "trans-20_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-34.
	****** File "trans-20_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-35.
	****** File "trans-20_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-36.
	****** File "trans-20_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-37.
	****** File "trans-20_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-38.
	****** File "trans-20_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-39.
	****** File "trans-20_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-40.
	****** File "trans-20_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-41.
	****** File "trans-20_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-42.
	****** File "trans-20_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-43.
	****** File "trans-20_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-44.
	****** File "trans-20_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-45.
	****** File "trans-20_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-46.
	****** File "trans-20_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-47.
	****** File "trans-20_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-48.
	****** File "trans-20_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 20-49.
	****** File "trans-20_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-21.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02562777263183
	Reading Transition Density: 21-22.
	****** File "trans-21_22.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-23.
	****** File "trans-21_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-24.
	****** File "trans-21_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-25.
	****** File "trans-21_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-26.
	****** File "trans-21_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-27.
	****** File "trans-21_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-28.
	****** File "trans-21_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-29.
	****** File "trans-21_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-30.
	****** File "trans-21_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-31.
	****** File "trans-21_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-32.
	****** File "trans-21_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-33.
	****** File "trans-21_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-34.
	****** File "trans-21_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-35.
	****** File "trans-21_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-36.
	****** File "trans-21_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-37.
	****** File "trans-21_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-38.
	****** File "trans-21_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-39.
	****** File "trans-21_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-40.
	****** File "trans-21_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-41.
	****** File "trans-21_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-42.
	****** File "trans-21_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-43.
	****** File "trans-21_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-44.
	****** File "trans-21_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-45.
	****** File "trans-21_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-46.
	****** File "trans-21_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-47.
	****** File "trans-21_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-48.
	****** File "trans-21_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 21-49.
	****** File "trans-21_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-22.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02558089764365
	Reading Transition Density: 22-23.
	****** File "trans-22_23.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-24.
	****** File "trans-22_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-25.
	****** File "trans-22_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-26.
	****** File "trans-22_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-27.
	****** File "trans-22_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-28.
	****** File "trans-22_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-29.
	****** File "trans-22_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-30.
	****** File "trans-22_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-31.
	****** File "trans-22_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-32.
	****** File "trans-22_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-33.
	****** File "trans-22_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-34.
	****** File "trans-22_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-35.
	****** File "trans-22_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-36.
	****** File "trans-22_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-37.
	****** File "trans-22_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-38.
	****** File "trans-22_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-39.
	****** File "trans-22_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-40.
	****** File "trans-22_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-41.
	****** File "trans-22_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-42.
	****** File "trans-22_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-43.
	****** File "trans-22_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-44.
	****** File "trans-22_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-45.
	****** File "trans-22_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-46.
	****** File "trans-22_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-47.
	****** File "trans-22_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-48.
	****** File "trans-22_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 22-49.
	****** File "trans-22_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-23.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025770509341754
	Reading Transition Density: 23-24.
	****** File "trans-23_24.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-25.
	****** File "trans-23_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-26.
	****** File "trans-23_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-27.
	****** File "trans-23_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-28.
	****** File "trans-23_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-29.
	****** File "trans-23_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-30.
	****** File "trans-23_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-31.
	****** File "trans-23_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-32.
	****** File "trans-23_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-33.
	****** File "trans-23_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-34.
	****** File "trans-23_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-35.
	****** File "trans-23_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-36.
	****** File "trans-23_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-37.
	****** File "trans-23_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-38.
	****** File "trans-23_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-39.
	****** File "trans-23_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-40.
	****** File "trans-23_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-41.
	****** File "trans-23_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-42.
	****** File "trans-23_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-43.
	****** File "trans-23_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-44.
	****** File "trans-23_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-45.
	****** File "trans-23_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-46.
	****** File "trans-23_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-47.
	****** File "trans-23_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-48.
	****** File "trans-23_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 23-49.
	****** File "trans-23_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-24.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025526368298706
	Reading Transition Density: 24-25.
	****** File "trans-24_25.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-26.
	****** File "trans-24_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-27.
	****** File "trans-24_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-28.
	****** File "trans-24_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-29.
	****** File "trans-24_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-30.
	****** File "trans-24_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-31.
	****** File "trans-24_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-32.
	****** File "trans-24_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-33.
	****** File "trans-24_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-34.
	****** File "trans-24_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-35.
	****** File "trans-24_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-36.
	****** File "trans-24_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-37.
	****** File "trans-24_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-38.
	****** File "trans-24_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-39.
	****** File "trans-24_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-40.
	****** File "trans-24_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-41.
	****** File "trans-24_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-42.
	****** File "trans-24_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-43.
	****** File "trans-24_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-44.
	****** File "trans-24_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-45.
	****** File "trans-24_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-46.
	****** File "trans-24_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-47.
	****** File "trans-24_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-48.
	****** File "trans-24_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 24-49.
	****** File "trans-24_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-25.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02611920545224
	Reading Transition Density: 25-26.
	****** File "trans-25_26.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-27.
	****** File "trans-25_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-28.
	****** File "trans-25_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-29.
	****** File "trans-25_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-30.
	****** File "trans-25_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-31.
	****** File "trans-25_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-32.
	****** File "trans-25_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-33.
	****** File "trans-25_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-34.
	****** File "trans-25_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-35.
	****** File "trans-25_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-36.
	****** File "trans-25_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-37.
	****** File "trans-25_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-38.
	****** File "trans-25_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-39.
	****** File "trans-25_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-40.
	****** File "trans-25_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-41.
	****** File "trans-25_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-42.
	****** File "trans-25_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-43.
	****** File "trans-25_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-44.
	****** File "trans-25_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-45.
	****** File "trans-25_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-46.
	****** File "trans-25_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-47.
	****** File "trans-25_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-48.
	****** File "trans-25_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 25-49.
	****** File "trans-25_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-26.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02573620940809
	Reading Transition Density: 26-27.
	****** File "trans-26_27.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-28.
	****** File "trans-26_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-29.
	****** File "trans-26_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-30.
	****** File "trans-26_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-31.
	****** File "trans-26_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-32.
	****** File "trans-26_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-33.
	****** File "trans-26_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-34.
	****** File "trans-26_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-35.
	****** File "trans-26_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-36.
	****** File "trans-26_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-37.
	****** File "trans-26_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-38.
	****** File "trans-26_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-39.
	****** File "trans-26_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-40.
	****** File "trans-26_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-41.
	****** File "trans-26_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-42.
	****** File "trans-26_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-43.
	****** File "trans-26_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-44.
	****** File "trans-26_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-45.
	****** File "trans-26_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-46.
	****** File "trans-26_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-47.
	****** File "trans-26_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-48.
	****** File "trans-26_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 26-49.
	****** File "trans-26_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-27.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02594783544502
	Reading Transition Density: 27-28.
	****** File "trans-27_28.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-29.
	****** File "trans-27_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-30.
	****** File "trans-27_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-31.
	****** File "trans-27_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-32.
	****** File "trans-27_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-33.
	****** File "trans-27_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-34.
	****** File "trans-27_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-35.
	****** File "trans-27_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-36.
	****** File "trans-27_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-37.
	****** File "trans-27_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-38.
	****** File "trans-27_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-39.
	****** File "trans-27_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-40.
	****** File "trans-27_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-41.
	****** File "trans-27_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-42.
	****** File "trans-27_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-43.
	****** File "trans-27_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-44.
	****** File "trans-27_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-45.
	****** File "trans-27_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-46.
	****** File "trans-27_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-47.
	****** File "trans-27_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-48.
	****** File "trans-27_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 27-49.
	****** File "trans-27_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-28.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.026420842842626
	Reading Transition Density: 28-29.
	****** File "trans-28_29.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-30.
	****** File "trans-28_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-31.
	****** File "trans-28_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-32.
	****** File "trans-28_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-33.
	****** File "trans-28_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-34.
	****** File "trans-28_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-35.
	****** File "trans-28_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-36.
	****** File "trans-28_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-37.
	****** File "trans-28_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-38.
	****** File "trans-28_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-39.
	****** File "trans-28_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-40.
	****** File "trans-28_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-41.
	****** File "trans-28_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-42.
	****** File "trans-28_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-43.
	****** File "trans-28_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-44.
	****** File "trans-28_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-45.
	****** File "trans-28_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-46.
	****** File "trans-28_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-47.
	****** File "trans-28_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-48.
	****** File "trans-28_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 28-49.
	****** File "trans-28_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-29.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02442363632935
	Reading Transition Density: 29-30.
	****** File "trans-29_30.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-31.
	****** File "trans-29_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-32.
	****** File "trans-29_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-33.
	****** File "trans-29_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-34.
	****** File "trans-29_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-35.
	****** File "trans-29_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-36.
	****** File "trans-29_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-37.
	****** File "trans-29_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-38.
	****** File "trans-29_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-39.
	****** File "trans-29_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-40.
	****** File "trans-29_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-41.
	****** File "trans-29_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-42.
	****** File "trans-29_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-43.
	****** File "trans-29_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-44.
	****** File "trans-29_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-45.
	****** File "trans-29_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-46.
	****** File "trans-29_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-47.
	****** File "trans-29_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-48.
	****** File "trans-29_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 29-49.
	****** File "trans-29_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-30.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.0255072500181
	Reading Transition Density: 30-31.
	****** File "trans-30_31.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-32.
	****** File "trans-30_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-33.
	****** File "trans-30_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-34.
	****** File "trans-30_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-35.
	****** File "trans-30_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-36.
	****** File "trans-30_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-37.
	****** File "trans-30_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-38.
	****** File "trans-30_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-39.
	****** File "trans-30_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-40.
	****** File "trans-30_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-41.
	****** File "trans-30_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-42.
	****** File "trans-30_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-43.
	****** File "trans-30_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-44.
	****** File "trans-30_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-45.
	****** File "trans-30_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-46.
	****** File "trans-30_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-47.
	****** File "trans-30_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-48.
	****** File "trans-30_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 30-49.
	****** File "trans-30_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-31.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.024963968438676
	Reading Transition Density: 31-32.
	****** File "trans-31_32.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-33.
	****** File "trans-31_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-34.
	****** File "trans-31_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-35.
	****** File "trans-31_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-36.
	****** File "trans-31_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-37.
	****** File "trans-31_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-38.
	****** File "trans-31_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-39.
	****** File "trans-31_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-40.
	****** File "trans-31_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-41.
	****** File "trans-31_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-42.
	****** File "trans-31_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-43.
	****** File "trans-31_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-44.
	****** File "trans-31_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-45.
	****** File "trans-31_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-46.
	****** File "trans-31_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-47.
	****** File "trans-31_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-48.
	****** File "trans-31_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 31-49.
	****** File "trans-31_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-32.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02612851309444
	Reading Transition Density: 32-33.
	****** File "trans-32_33.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-34.
	****** File "trans-32_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-35.
	****** File "trans-32_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-36.
	****** File "trans-32_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-37.
	****** File "trans-32_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-38.
	****** File "trans-32_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-39.
	****** File "trans-32_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-40.
	****** File "trans-32_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-41.
	****** File "trans-32_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-42.
	****** File "trans-32_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-43.
	****** File "trans-32_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-44.
	****** File "trans-32_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-45.
	****** File "trans-32_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-46.
	****** File "trans-32_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-47.
	****** File "trans-32_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-48.
	****** File "trans-32_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 32-49.
	****** File "trans-32_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-33.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.0257323141466
	Reading Transition Density: 33-34.
	****** File "trans-33_34.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-35.
	****** File "trans-33_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-36.
	****** File "trans-33_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-37.
	****** File "trans-33_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-38.
	****** File "trans-33_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-39.
	****** File "trans-33_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-40.
	****** File "trans-33_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-41.
	****** File "trans-33_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-42.
	****** File "trans-33_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-43.
	****** File "trans-33_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-44.
	****** File "trans-33_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-45.
	****** File "trans-33_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-46.
	****** File "trans-33_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-47.
	****** File "trans-33_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-48.
	****** File "trans-33_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 33-49.
	****** File "trans-33_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-34.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02542984576765
	Reading Transition Density: 34-35.
	****** File "trans-34_35.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-36.
	****** File "trans-34_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-37.
	****** File "trans-34_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-38.
	****** File "trans-34_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-39.
	****** File "trans-34_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-40.
	****** File "trans-34_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-41.
	****** File "trans-34_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-42.
	****** File "trans-34_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-43.
	****** File "trans-34_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-44.
	****** File "trans-34_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-45.
	****** File "trans-34_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-46.
	****** File "trans-34_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-47.
	****** File "trans-34_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-48.
	****** File "trans-34_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 34-49.
	****** File "trans-34_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-35.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02451793388603
	Reading Transition Density: 35-36.
	****** File "trans-35_36.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-37.
	****** File "trans-35_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-38.
	****** File "trans-35_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-39.
	****** File "trans-35_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-40.
	****** File "trans-35_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-41.
	****** File "trans-35_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-42.
	****** File "trans-35_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-43.
	****** File "trans-35_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-44.
	****** File "trans-35_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-45.
	****** File "trans-35_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-46.
	****** File "trans-35_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-47.
	****** File "trans-35_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-48.
	****** File "trans-35_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 35-49.
	****** File "trans-35_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-36.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02580400065232
	Reading Transition Density: 36-37.
	****** File "trans-36_37.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-38.
	****** File "trans-36_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-39.
	****** File "trans-36_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-40.
	****** File "trans-36_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-41.
	****** File "trans-36_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-42.
	****** File "trans-36_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-43.
	****** File "trans-36_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-44.
	****** File "trans-36_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-45.
	****** File "trans-36_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-46.
	****** File "trans-36_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-47.
	****** File "trans-36_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-48.
	****** File "trans-36_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 36-49.
	****** File "trans-36_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-37.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025759437098905
	Reading Transition Density: 37-38.
	****** File "trans-37_38.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-39.
	****** File "trans-37_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-40.
	****** File "trans-37_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-41.
	****** File "trans-37_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-42.
	****** File "trans-37_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-43.
	****** File "trans-37_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-44.
	****** File "trans-37_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-45.
	****** File "trans-37_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-46.
	****** File "trans-37_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-47.
	****** File "trans-37_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-48.
	****** File "trans-37_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 37-49.
	****** File "trans-37_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-38.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02672757427369
	Reading Transition Density: 38-39.
	****** File "trans-38_39.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-40.
	****** File "trans-38_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-41.
	****** File "trans-38_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-42.
	****** File "trans-38_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-43.
	****** File "trans-38_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-44.
	****** File "trans-38_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-45.
	****** File "trans-38_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-46.
	****** File "trans-38_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-47.
	****** File "trans-38_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-48.
	****** File "trans-38_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 38-49.
	****** File "trans-38_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 39-39.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02629524001737
	Reading Transition Density: 39-40.
	****** File "trans-39_40.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 39-41.
	****** File "trans-39_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 39-42.
	****** File "trans-39_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 39-43.
	****** File "trans-39_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 39-44.
	****** File "trans-39_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 39-45.
	****** File "trans-39_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 39-46.
	****** File "trans-39_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 39-47.
	****** File "trans-39_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 39-48.
	****** File "trans-39_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 39-49.
	****** File "trans-39_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 40-40.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02646216113847
	Reading Transition Density: 40-41.
	****** File "trans-40_41.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 40-42.
	****** File "trans-40_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 40-43.
	****** File "trans-40_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 40-44.
	****** File "trans-40_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 40-45.
	****** File "trans-40_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 40-46.
	****** File "trans-40_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 40-47.
	****** File "trans-40_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 40-48.
	****** File "trans-40_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 40-49.
	****** File "trans-40_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 41-41.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02594361674145
	Reading Transition Density: 41-42.
	****** File "trans-41_42.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 41-43.
	****** File "trans-41_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 41-44.
	****** File "trans-41_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 41-45.
	****** File "trans-41_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 41-46.
	****** File "trans-41_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 41-47.
	****** File "trans-41_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 41-48.
	****** File "trans-41_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 41-49.
	****** File "trans-41_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 42-42.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02579938033765
	Reading Transition Density: 42-43.
	****** File "trans-42_43.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 42-44.
	****** File "trans-42_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 42-45.
	****** File "trans-42_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 42-46.
	****** File "trans-42_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 42-47.
	****** File "trans-42_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 42-48.
	****** File "trans-42_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 42-49.
	****** File "trans-42_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 43-43.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02592823106537
	Reading Transition Density: 43-44.
	****** File "trans-43_44.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 43-45.
	****** File "trans-43_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 43-46.
	****** File "trans-43_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 43-47.
	****** File "trans-43_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 43-48.
	****** File "trans-43_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 43-49.
	****** File "trans-43_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 44-44.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02573146252353
	Reading Transition Density: 44-45.
	****** File "trans-44_45.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 44-46.
	****** File "trans-44_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 44-47.
	****** File "trans-44_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 44-48.
	****** File "trans-44_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 44-49.
	****** File "trans-44_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 45-45.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02606694755004
	Reading Transition Density: 45-46.
	****** File "trans-45_46.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 45-47.
	****** File "trans-45_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 45-48.
	****** File "trans-45_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 45-49.
	****** File "trans-45_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 46-46.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02646478813177
	Reading Transition Density: 46-47.
	****** File "trans-46_47.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 46-48.
	****** File "trans-46_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 46-49.
	****** File "trans-46_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 47-47.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.02451295864585
	Reading Transition Density: 47-48.
	****** File "trans-47_48.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 47-49.
	****** File "trans-47_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 48-48.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.024917864327264
	Reading Transition Density: 48-49.
	****** File "trans-48_49.cube" not found. Skipping this matrix element. ******
	Reading Transition Density: 49-49.
I FOUND QCHEM ERROR ! Multiplying non-ground state densities by factor of 2...
Skipping diagonal density normalization: norm = 63.025734345970235
Diagonal Density (A0 = 0.0)
Non-zero contributions to diagonal Density for state P0:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 0 0 1.0 1.0 1.0
Non-zero contributions to diagonal Density for state P1:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
1 0 0 1.0 1.0 1.0
Non-zero contributions to diagonal Density for state P2:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 1 1 1.0 1.0 1.0
Non-zero contributions to diagonal Density for state P3:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 2 2 1.0 1.0 1.0
Non-zero contributions to diagonal Density for state P4:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 3 3 1.0 1.0 1.0
Non-zero contributions to diagonal Density for state P5:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 4 4 1.0 1.0 1.0
Diagonal Density (A0 = 0.01)
Non-zero contributions to diagonal Density for state P0:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 0 0 1.0 1.0 1.0
Non-zero contributions to diagonal Density for state P1:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
1 0 0 -0.9999 -0.9999 0.9997
Non-zero contributions to diagonal Density for state P2:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 1 1 -0.9999 -0.9999 0.9998
Non-zero contributions to diagonal Density for state P3:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 2 2 0.9998 0.9998 0.9996
Non-zero contributions to diagonal Density for state P4:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 3 3 0.9999 0.9999 0.9999
Non-zero contributions to diagonal Density for state P5:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 4 4 1.0 1.0 1.0
Diagonal Density (A0 = 0.05)
Non-zero contributions to diagonal Density for state P0:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 0 0 0.9996 0.9996 0.9992
Non-zero contributions to diagonal Density for state P1:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 12 12 0.0485 0.0485 0.0024
1 0 0 0.9968 0.9968 0.9936
Non-zero contributions to diagonal Density for state P2:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 1 1 -0.9974 -0.9974 0.9949
1 2 2 0.0683 0.0683 0.0047
Non-zero contributions to diagonal Density for state P3:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 2 2 0.9954 0.9954 0.9907
1 1 1 -0.0946 -0.0946 0.0089
Non-zero contributions to diagonal Density for state P4:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 3 3 0.9985 0.9985 0.9969
1 0 17 -0.0313 -0.0379 0.0012
1 17 0 -0.0379 -0.0313 0.0012
1 17 17 -0.0379 -0.0379 0.0014
Non-zero contributions to diagonal Density for state P5:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 4 4 0.9996 0.9996 0.9993
Diagonal Density (A0 = 0.1)
Non-zero contributions to diagonal Density for state P0:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 0 0 -0.9984 -0.9984 0.9968
0 0 15 -0.9984 -0.0029 0.0029
0 0 17 -0.9984 -0.0033 0.0033
0 0 34 -0.9984 -0.0032 0.0032
0 0 35 -0.9984 -0.0023 0.0023
0 15 0 -0.0029 -0.9984 0.0029
0 17 0 -0.0033 -0.9984 0.0033
0 34 0 -0.0032 -0.9984 0.0032
0 35 0 -0.0023 -0.9984 0.0023
1 12 12 -0.0444 -0.0444 0.002
Non-zero contributions to diagonal Density for state P1:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 3 3 -0.0591 -0.0591 0.0035
0 5 5 -0.0446 -0.0446 0.002
0 6 6 0.0571 0.0571 0.0033
0 12 12 -0.0926 -0.0926 0.0086
1 0 0 -0.988 -0.988 0.9761
1 0 4 -0.988 -0.001 0.001
1 0 44 -0.988 -0.0012 0.0012
1 4 0 -0.001 -0.988 0.001
1 44 0 -0.0012 -0.988 0.0012
2 6 6 0.0318 0.0318 0.001
2 12 12 -0.0626 -0.0626 0.0039
Non-zero contributions to diagonal Density for state P2:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 1 1 0.9895 0.9895 0.9791
1 2 2 -0.1366 -0.1366 0.0187
Non-zero contributions to diagonal Density for state P3:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 2 2 -0.9817 -0.9817 0.9636
1 1 1 0.186 0.186 0.0346
Non-zero contributions to diagonal Density for state P4:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 3 3 0.9939 0.9939 0.9879
MISSING!!! 0 3 6 0.9939 0.0102 0.0101
MISSING!!! 0 6 3 0.0102 0.9939 0.0101
1 0 0 -0.0572 -0.0572 0.0033
1 0 4 -0.0572 -0.023 0.0013
1 0 7 -0.0572 -0.0377 0.0022
1 0 17 -0.0572 -0.076 0.0043
1 4 0 -0.023 -0.0572 0.0013
1 7 0 -0.0377 -0.0572 0.0022
1 7 7 -0.0377 -0.0377 0.0014
1 17 0 -0.076 -0.0572 0.0043
1 17 17 -0.076 -0.076 0.0058
Non-zero contributions to diagonal Density for state P5:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 0 4 -0.0022 -0.9981 0.0022
0 4 0 -0.9981 -0.0022 0.0022
0 4 4 -0.9981 -0.9981 0.9963
1 6 6 0.0317 0.0317 0.001
Diagonal Density (A0 = 0.2)
Non-zero contributions to diagonal Density for state P0:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 0 0 0.9931 0.9931 0.9862
0 0 15 0.9931 0.0114 0.0113
0 0 17 0.9931 0.013 0.0129
0 0 34 0.9931 0.0127 0.0126
0 0 35 0.9931 0.009 0.0089
0 15 0 0.0114 0.9931 0.0113
0 17 0 0.013 0.9931 0.0129
0 34 0 0.0127 0.9931 0.0126
0 35 0 0.009 0.9931 0.0089
1 5 5 0.0327 0.0327 0.0011
1 6 6 -0.0433 -0.0433 0.0019
1 12 12 0.0861 0.0861 0.0074
Non-zero contributions to diagonal Density for state P1:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 3 3 -0.0955 -0.0955 0.0091
MISSING!!! 0 3 12 -0.0955 -0.1573 0.015
0 5 5 -0.0781 -0.0781 0.0061
MISSING!!! 0 5 12 -0.0781 -0.1573 0.0123
0 6 6 0.095 0.095 0.009
MISSING!!! 0 12 3 -0.1573 -0.0955 0.015
MISSING!!! 0 12 5 -0.1573 -0.0781 0.0123
0 12 12 -0.1573 -0.1573 0.0247
1 0 0 -0.9612 -0.9612 0.9239
1 0 4 -0.9612 -0.0022 0.0021
1 0 13 -0.9612 -0.0022 0.0021
1 0 35 -0.9612 -0.0017 0.0017
1 0 43 -0.9612 -0.0017 0.0016
1 0 44 -0.9612 -0.0041 0.0039
1 4 0 -0.0022 -0.9612 0.0021
1 13 0 -0.0022 -0.9612 0.0021
1 35 0 -0.0017 -0.9612 0.0017
1 43 0 -0.0017 -0.9612 0.0016
1 44 0 -0.0041 -0.9612 0.0039
2 3 3 -0.0423 -0.0423 0.0018
2 5 5 -0.0446 -0.0446 0.002
2 6 6 0.062 0.062 0.0038
2 12 12 -0.1214 -0.1214 0.0147
3 0 0 -0.0488 -0.0488 0.0024
Non-zero contributions to diagonal Density for state P2:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 1 1 0.9551 0.9551 0.9121
1 2 2 -0.2726 -0.2726 0.0743
MISSING!!! 1 2 10 -0.2726 -0.0438 0.0119
MISSING!!! 1 10 2 -0.0438 -0.2726 0.0119
1 10 10 -0.0438 -0.0438 0.0019
1 25 25 0.0381 0.0381 0.0015
1 38 38 -0.0366 -0.0366 0.0013
2 1 1 0.077 0.077 0.0059
Non-zero contributions to diagonal Density for state P3:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 2 2 -0.93 -0.93 0.8649
MISSING!!! 0 2 9 -0.93 -0.0182 0.017
MISSING!!! 0 9 2 -0.0182 -0.93 0.017
1 1 1 0.3488 0.3488 0.1216
2 2 2 -0.0868 -0.0868 0.0075
Non-zero contributions to diagonal Density for state P4:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 3 3 0.976 0.976 0.9525
MISSING!!! 0 3 6 0.976 0.0296 0.0289
MISSING!!! 0 3 19 0.976 0.0105 0.0102
0 5 5 -0.0317 -0.0317 0.001
MISSING!!! 0 6 3 0.0296 0.976 0.0289
0 12 12 -0.0377 -0.0377 0.0014
MISSING!!! 0 19 3 0.0105 0.976 0.0102
1 0 0 -0.0854 -0.0854 0.0073
1 0 4 -0.0854 -0.0534 0.0046
1 0 7 -0.0854 -0.0709 0.0061
1 0 17 -0.0854 -0.1529 0.0131
1 0 43 -0.0854 -0.0363 0.0031
1 4 0 -0.0534 -0.0854 0.0046
1 4 4 -0.0534 -0.0534 0.0029
1 7 0 -0.0709 -0.0854 0.0061
1 7 7 -0.0709 -0.0709 0.005
MISSING!!! 1 7 17 -0.0709 -0.1529 0.0108
1 17 0 -0.1529 -0.0854 0.0131
MISSING!!! 1 17 7 -0.1529 -0.0709 0.0108
1 17 17 -0.1529 -0.1529 0.0234
1 43 0 -0.0363 -0.0854 0.0031
1 43 43 -0.0363 -0.0363 0.0013
2 3 3 0.0452 0.0452 0.002
Non-zero contributions to diagonal Density for state P5:
n, j, k, C_{jn}, C_{kn}, P_{jn,kn}
0 0 4 -0.0017 -0.9787 0.0017
0 4 0 -0.9787 -0.0017 0.0017
0 4 4 -0.9787 -0.9787 0.9579
MISSING!!! 0 4 7 -0.9787 -0.0218 0.0213
MISSING!!! 0 7 4 -0.0218 -0.9787 0.0213
1 3 3 0.0346 0.0346 0.0012
1 5 5 -0.0587 -0.0587 0.0035
1 6 6 0.0735 0.0735 0.0054
1 12 12 -0.0661 -0.0661 0.0044
2 0 0 -0.1588 -0.1588 0.0252
2 0 4 -0.1588 -0.012 0.0019
2 0 43 -0.1588 -0.0119 0.0019
2 4 0 -0.012 -0.1588 0.0019
2 43 0 -0.0119 -0.1588 0.0019
Writing diagonal density file. p: 0-->0, A0 = 0.0
Writing diagonal density file. p: 0-->0, A0 = 0.01
Writing diagonal density file. p: 0-->0, A0 = 0.05
Writing diagonal density file. p: 0-->0, A0 = 0.1
Writing diagonal density file. p: 0-->0, A0 = 0.2
Writing diagonal density file. p: 1-->1, A0 = 0.0
Writing diagonal density file. p: 1-->1, A0 = 0.01
Writing diagonal density file. p: 1-->1, A0 = 0.05
Writing diagonal density file. p: 1-->1, A0 = 0.1
Writing diagonal density file. p: 1-->1, A0 = 0.2
Writing diagonal density file. p: 2-->2, A0 = 0.0
Writing diagonal density file. p: 2-->2, A0 = 0.01
Writing diagonal density file. p: 2-->2, A0 = 0.05
Writing diagonal density file. p: 2-->2, A0 = 0.1
Writing diagonal density file. p: 2-->2, A0 = 0.2
Writing diagonal density file. p: 3-->3, A0 = 0.0
Writing diagonal density file. p: 3-->3, A0 = 0.01
Writing diagonal density file. p: 3-->3, A0 = 0.05
Writing diagonal density file. p: 3-->3, A0 = 0.1
Writing diagonal density file. p: 3-->3, A0 = 0.2
Writing diagonal density file. p: 4-->4, A0 = 0.0
Writing diagonal density file. p: 4-->4, A0 = 0.01
Writing diagonal density file. p: 4-->4, A0 = 0.05
Writing diagonal density file. p: 4-->4, A0 = 0.1
Writing diagonal density file. p: 4-->4, A0 = 0.2
Writing diagonal density file. p: 5-->5, A0 = 0.0
Writing diagonal density file. p: 5-->5, A0 = 0.01
Writing diagonal density file. p: 5-->5, A0 = 0.05
Writing diagonal density file. p: 5-->5, A0 = 0.1
Writing diagonal density file. p: 5-->5, A0 = 0.2
Writing difference density file. option = 00_cavity_no-cavity, A0 = 0.0
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 00_cavity_no-cavity, A0 = 0.01
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 00_cavity_no-cavity, A0 = 0.05
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 00_cavity_no-cavity, A0 = 0.1
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 00_cavity_no-cavity, A0 = 0.2
Length of RGrid: 75 500
Length of function: 75 500
Writing the difference density (00_cavity_no-cavity) contour data to a file (A0 = 0.0).
Writing the difference density (00_cavity_no-cavity) contour data to a file (A0 = 0.01).
Writing the difference density (00_cavity_no-cavity) contour data to a file (A0 = 0.05).
Writing the difference density (00_cavity_no-cavity) contour data to a file (A0 = 0.1).
Writing the difference density (00_cavity_no-cavity) contour data to a file (A0 = 0.2).
Writing difference density file. option = 11_cavity_no-cavity, A0 = 0.0
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 11_cavity_no-cavity, A0 = 0.01
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 11_cavity_no-cavity, A0 = 0.05
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 11_cavity_no-cavity, A0 = 0.1
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 11_cavity_no-cavity, A0 = 0.2
Length of RGrid: 75 500
Length of function: 75 500
Writing the difference density (11_cavity_no-cavity) contour data to a file (A0 = 0.0).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-163.77715560000007,284.4527269999997) m|e|/A^2
Writing the difference density (11_cavity_no-cavity) contour data to a file (A0 = 0.01).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-163.75650801985643,284.4529257395352) m|e|/A^2
Writing the difference density (11_cavity_no-cavity) contour data to a file (A0 = 0.05).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-163.27522577326513,284.45727081359087) m|e|/A^2
Writing the difference density (11_cavity_no-cavity) contour data to a file (A0 = 0.1).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-161.9274683994144,284.46592938703753) m|e|/A^2
Writing the difference density (11_cavity_no-cavity) contour data to a file (A0 = 0.2).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-158.1044652186272,284.44261769555237) m|e|/A^2
Writing difference density file. option = 21_cavity_no-cavity, A0 = 0.0
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 21_cavity_no-cavity, A0 = 0.01
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 21_cavity_no-cavity, A0 = 0.05
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 21_cavity_no-cavity, A0 = 0.1
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 21_cavity_no-cavity, A0 = 0.2
Length of RGrid: 75 500
Length of function: 75 500
Writing the difference density (21_cavity_no-cavity) contour data to a file (A0 = 0.0).
Writing the difference density (21_cavity_no-cavity) contour data to a file (A0 = 0.01).
Writing the difference density (21_cavity_no-cavity) contour data to a file (A0 = 0.05).
Writing the difference density (21_cavity_no-cavity) contour data to a file (A0 = 0.1).
Writing the difference density (21_cavity_no-cavity) contour data to a file (A0 = 0.2).
Writing difference density file. option = 10_cavity, A0 = 0.0
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 10_cavity, A0 = 0.01
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 10_cavity, A0 = 0.05
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 10_cavity, A0 = 0.1
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 10_cavity, A0 = 0.2
Length of RGrid: 75 500
Length of function: 75 500
Writing the difference density (10_cavity) contour data to a file (A0 = 0.0).
Writing the difference density (10_cavity) contour data to a file (A0 = 0.01).
Writing the difference density (10_cavity) contour data to a file (A0 = 0.05).
Writing the difference density (10_cavity) contour data to a file (A0 = 0.1).
Writing the difference density (10_cavity) contour data to a file (A0 = 0.2).
Writing difference density file. option = 10_no-cavity, A0 = 0.0
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 10_no-cavity, A0 = 0.01
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 10_no-cavity, A0 = 0.05
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 10_no-cavity, A0 = 0.1
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 10_no-cavity, A0 = 0.2
Length of RGrid: 75 500
Length of function: 75 500
Writing the difference density (10_no-cavity) contour data to a file (A0 = 0.0).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-284.4527269999997,163.77715560000007) m|e|/A^2
Writing the difference density (10_no-cavity) contour data to a file (A0 = 0.01).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-284.4527269999997,163.77715560000007) m|e|/A^2
Writing the difference density (10_no-cavity) contour data to a file (A0 = 0.05).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-284.4527269999997,163.77715560000007) m|e|/A^2
Writing the difference density (10_no-cavity) contour data to a file (A0 = 0.1).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-284.4527269999997,163.77715560000007) m|e|/A^2
Writing the difference density (10_no-cavity) contour data to a file (A0 = 0.2).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-284.4527269999997,163.77715560000007) m|e|/A^2
Writing difference density file. option = 20_cavity, A0 = 0.0
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 20_cavity, A0 = 0.01
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 20_cavity, A0 = 0.05
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 20_cavity, A0 = 0.1
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 20_cavity, A0 = 0.2
Length of RGrid: 75 500
Length of function: 75 500
Writing the difference density (20_cavity) contour data to a file (A0 = 0.0).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-284.4527269999997,163.77715560000007) m|e|/A^2
Writing the difference density (20_cavity) contour data to a file (A0 = 0.01).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-284.416303934385,163.7814063487163) m|e|/A^2
Writing the difference density (20_cavity) contour data to a file (A0 = 0.05).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-283.5414401168363,163.88298548753966) m|e|/A^2
Writing the difference density (20_cavity) contour data to a file (A0 = 0.1).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-280.8001590373612,164.19498659634792) m|e|/A^2
Writing the difference density (20_cavity) contour data to a file (A0 = 0.2).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-269.8143783952931,165.36079257614466) m|e|/A^2
Writing difference density file. option = 21_cavity, A0 = 0.0
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 21_cavity, A0 = 0.01
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 21_cavity, A0 = 0.05
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 21_cavity, A0 = 0.1
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 21_cavity, A0 = 0.2
Length of RGrid: 75 500
Length of function: 75 500
Writing the difference density (21_cavity) contour data to a file (A0 = 0.0).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-284.4527269999997,163.77715560000007) m|e|/A^2
Writing the difference density (21_cavity) contour data to a file (A0 = 0.01).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-284.42029139587044,163.7541544988943) m|e|/A^2
Writing the difference density (21_cavity) contour data to a file (A0 = 0.05).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-283.6407085525314,163.21639253178165) m|e|/A^2
Writing the difference density (21_cavity) contour data to a file (A0 = 0.1).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-281.1923149610558,161.69224203311794) m|e|/A^2
Writing the difference density (21_cavity) contour data to a file (A0 = 0.2).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-271.3193948875929,157.16806913021986) m|e|/A^2
Writing difference density file. option = 40_no-cavity, A0 = 0.0
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 40_no-cavity, A0 = 0.01
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 40_no-cavity, A0 = 0.05
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 40_no-cavity, A0 = 0.1
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 40_no-cavity, A0 = 0.2
Length of RGrid: 75 500
Length of function: 75 500
Writing the difference density (40_no-cavity) contour data to a file (A0 = 0.0).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-55.69958200000003,122.42693800000004) m|e|/A^2
Writing the difference density (40_no-cavity) contour data to a file (A0 = 0.01).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-55.69958200000003,122.42693800000004) m|e|/A^2
Writing the difference density (40_no-cavity) contour data to a file (A0 = 0.05).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-55.69958200000003,122.42693800000004) m|e|/A^2
Writing the difference density (40_no-cavity) contour data to a file (A0 = 0.1).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-55.69958200000003,122.42693800000004) m|e|/A^2
Writing the difference density (40_no-cavity) contour data to a file (A0 = 0.2).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-55.69958200000003,122.42693800000004) m|e|/A^2
Writing difference density file. option = 40_cavity, A0 = 0.0
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 40_cavity, A0 = 0.01
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 40_cavity, A0 = 0.05
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 40_cavity, A0 = 0.1
Length of RGrid: 75 500
Length of function: 75 500
Writing difference density file. option = 40_cavity, A0 = 0.2
Length of RGrid: 75 500
Length of function: 75 500
Writing the difference density (40_cavity) contour data to a file (A0 = 0.0).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-30.699806599999935,93.54358800000017) m|e|/A^2
Writing the difference density (40_cavity) contour data to a file (A0 = 0.01).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-30.69511206154052,93.52489955348054) m|e|/A^2
Writing the difference density (40_cavity) contour data to a file (A0 = 0.05).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-30.58564050362822,93.08091888953518) m|e|/A^2
Writing the difference density (40_cavity) contour data to a file (A0 = 0.1).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-30.278127599075887,91.74352855087697) m|e|/A^2
Writing the difference density (40_cavity) contour data to a file (A0 = 0.2).

	WARNING!!!! SOMETHING WRONG WITH DIFFERENCE DENSITY!!!
	 (MIN,MAX) = (-29.377536498556456,89.1083758392065) m|e|/A^2
